---
- name: SET ROUTER BANNERS
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:

    - name: LOAD BANNER ONTO NETWORK DEVICE
      include_tasks: "{{ ansible_network_os }}_banner.yaml"
      vars:
        - network_banner:  "{{ net_banner | default(None) }}"
        - banner_type: "{{ banner_type | default('login') }}"
